<?php
$params = [
// COCHE SELECCIONADO PARA VENDER
    "no_vehiculo" => "7630948104250906",
    "id_modelo_fk" => "139",
    "fecha_registro_coche" => "14-jun-2021",
    "anio" => "2021",
    "placa" => "FFFFF-25542",
    "entidad_placa" => "",
    "color" => "Amarillo",
    "kilometros" => "15000",
    "transmision" => "MA",
    "combustible" => "DIESEL",
    "no_puertas" => 4,
    "precio_contado" => 10000.00,
    "precio_credito" => 15000.00,
    "opc_credito" => 1,
    "observaciones" => "",
    "estatusC" => 1,
    //CLIENTE - COMPRADOR DATOS
    "no_cliente" => "2572742",
    "nombre" => "Christian",
    "apaterno" => "Pioquinto",
    "amaterno" => "Hernandez",
    "telefono" => "5597091960",
    "celular" => "55987541365",
    "correo" => "chris@gmail.com",
    "subscripcion" => "1",
    "empresa" => "ReckreaStudios",
    "fecha_registro" => "FECHA AQUI",
    "medio_identificacion" => "1",
    "folio" => "50",
    "tipo_cliente" => "1",
    "estatusUs" => "1",
    //CONTRATO DATOS
    "no_empleado_fk" => "2",
    "no_cliente_fk" => "0",
    "no_vehiculo_fk" => "0",
    "hora_fecha_creacion" => "FechaDeCreacion",
    "tipo_contrato" => "0",
    "plazo" => "6",
    "fecha_primer_pago" => "FechaDePago1",
    "enganche" => "2000",
    "saldo" => "0",
    "forma_pago" => "1",
    "subtotal" => "8000",
    "iva" => "10",
    "total" => "8800",
    "estatusCon" => "0",
];

include_once "../control/controlContrato.php";
echo creaContratoVenta($params) ? "Se ha creado un contrato de Venta" : "Error al crear contrato";